-- add in your core/shared/items.lua

["fishbasin"]	        =  {["name"] = "fishbasin",	["label"] = "Fish Basin",	["weight"] = 12500,	["type"] = "item",	["image"] = "wood_barrel_fish_basin.png",	['unique'] = true,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "equipment for fishing"},
["fishbasin_ms"]	    =  {["name"] = "fishbasin_ms",	["label"] = "Fish Basin M",	["weight"] = 25000,	["type"] = "item",	["image"] = "wood_barrel_fish_basin.png",	['unique'] = true,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "equipment for fishing"},
["fishbasin_xl"]	    =  {["name"] = "fishbasin_xl",	["label"] = "Fish Basin XL",	["weight"] = 37500,	["type"] = "item",	["image"] = "wood_barrel_fish_basin.png",	['unique'] = true,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "equipment for fishing"},

['fishmeat']		= {['name'] = 'fishmeat',		['label'] = 'Filete de pescado malo',		--[[ ['decay'] = 2.0, ['delete'] = true,]] ['weight'] = 150, 	['type'] = 'item',	['image'] = 'meat_fish.png',		['unique'] = false,	    ['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'Raw Fish Meat'},
['smallfish']		= {['name'] = 'smallfish',		['label'] = 'Filete Pez (S)',				--[[ ['decay'] = 1.0, ['delete'] = true,]] ['weight'] = 100,	['type'] = 'item',	['image'] = 'meat_smallfish.png',	['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
['mediumfish']		= {['name'] = 'mediumfish',		['label'] = 'Filete Pez (M)',				--[[ ['decay'] = 2.0, ['delete'] = true,]] ['weight'] = 200,	['type'] = 'item',	['image'] = 'meat_mediumfish.png',	['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
['largefish']		= {['name'] = 'largefish',		['label'] = 'Filete Pez (L)',				--[[ ['decay'] = 2.0, ['delete'] = true,]] ['weight'] = 300,	['type'] = 'item',	['image'] = 'meat_largefish.png',	['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
