-- add in your core/shared/items.lua

["fishbasin_ms"]	    =  {["name"] = "fishbasin_ms",	["label"] = "Fish Basin M",	["weight"] = 25000,	["type"] = "item",	["image"] = "provision_barrel_meat_fish.png",	['unique'] = true,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "equipment for fishing"},
["fishbasin_xl"]	    =  {["name"] = "fishbasin_xl",	["label"] = "Fish Basin XL",	["weight"] = 37500,	["type"] = "item",	["image"] = "provision_barrel_meat_fish.png",	['unique'] = true,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "equipment for fishing"},

['fishmeat']		= {['name'] = 'fishmeat',		  ['label'] = 'Bad fish fillet',	      --[[ ['decay'] = 2.0, ['delete'] = true,]] ['weight'] = 150, 	['type'] = 'item',	['image'] = 'provision_meat_fish.png',		['unique'] = false,	    ['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'Raw Fish Meat'},
['smallfish']		= {['name'] = 'smallfish',		['label'] = 'Fish fillet (S)',				--[[ ['decay'] = 1.0, ['delete'] = true,]] ['weight'] = 100,	['type'] = 'item',	['image'] = 'provision_meat_smallfish.png',	['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
['mediumfish']	= {['name'] = 'mediumfish',		['label'] = 'Fish fillet (M)',				--[[ ['decay'] = 2.0, ['delete'] = true,]] ['weight'] = 200,	['type'] = 'item',	['image'] = 'provision_meat_mediumfish.png',	['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
['largefish']		= {['name'] = 'largefish',		['label'] = 'Fish fillet (L)',				--[[ ['decay'] = 2.0, ['delete'] = true,]] ['weight'] = 300,	['type'] = 'item',	['image'] = 'provision_meat_largefish.png',	['unique'] = false,	['useable'] = true,	['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
